// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDj5o4uHFdM5KUEFljolg6-gjVXzzKUa4',
    appId: '1:31904357952:android:4925c3875950d4e39d89a5',
    messagingSenderId: '31904357952',
    projectId: 'gainz-e9b6c',
    storageBucket: 'gainz-e9b6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdyOzaBSENtEXobuQtzDW-mgdEGc1bxiQ',
    appId: '1:31904357952:ios:fd5a1dc4c78e7a6e9d89a5',
    messagingSenderId: '31904357952',
    projectId: 'gainz-e9b6c',
    storageBucket: 'gainz-e9b6c.firebasestorage.app',
    iosBundleId: 'com.example.gainz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdyOzaBSENtEXobuQtzDW-mgdEGc1bxiQ',
    appId: '1:31904357952:ios:fd5a1dc4c78e7a6e9d89a5',
    messagingSenderId: '31904357952',
    projectId: 'gainz-e9b6c',
    storageBucket: 'gainz-e9b6c.firebasestorage.app',
    iosBundleId: 'com.example.gainz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCktQlyerOzxzsNx4A4kPYwBv2aZJBg8GE',
    appId: '1:31904357952:web:e842cce2024c35e59d89a5',
    messagingSenderId: '31904357952',
    projectId: 'gainz-e9b6c',
    authDomain: 'gainz-e9b6c.firebaseapp.com',
    storageBucket: 'gainz-e9b6c.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktQlyerOzxzsNx4A4kPYwBv2aZJBg8GE',
    appId: '1:31904357952:web:e842cce2024c35e59d89a5',
    messagingSenderId: '31904357952',
    projectId: 'gainz-e9b6c',
    authDomain: 'gainz-e9b6c.firebaseapp.com',
    storageBucket: 'gainz-e9b6c.firebasestorage.app',
  );

}